data<-read.csv("household_power_consumption.txt",sep = ";",header = T,stringsAsFactors = F)
data$Date<-as.Date(data$Date,"%d/%m/%Y")
data2<-subset(data,Date=="2007-02-01"|Date=="2007-02-02")
data2$Global_active_power<-as.numeric(data2$Global_active_power)
data2$Global_reactive_power<-as.numeric(data2$Global_reactive_power)
data2$Voltage<-as.numeric(data2$Voltage)
data2$Global_intensity<-as.numeric(data2$Global_intensity)
data2$Global_intensity<-as.numeric(data2$Global_intensity)
data2$Sub_metering_1<-as.numeric(data2$Sub_metering_1)
data2$Sub_metering_2<-as.numeric(data2$Sub_metering_2)
data2$Sub_metering_3<-as.numeric(data2$Sub_metering_3)
data2$datetime<-paste(data2$Date,data2$Time, sep = " ")
data2$datetime<-strptime(data2$datetime,"%Y-%m-%d %H:%M:%S")
png("plot1.png")
hist(data2$Global_active_power,col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()